on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please
jobs:
  release:
    name: release
    if: ${{ !failure() && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: release-please config
        id: release-please-config
        run: |
          if [ -f .github/release-please-config.json ]; then
            echo "config-file=.github/release-please-config.json" >> $GITHUB_OUTPUT
            [ -f .github/release-please-manifest.json ] &&
              echo "manifest-file=.github/release-please-manifest.json" >> $GITHUB_OUTPUT
          else
            echo "release-type=simple" >> $GITHUB_OUTPUT
          fi
          exit 0
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          config-file: ${{ steps.release-please-config.outputs.config-file }}
          release-type: ${{ steps.release-please-config.outputs.release-type }}
          manifest-file: ${{ steps.release-please-config.outputs.manifest-file }}
